Apply doc update to Japanese ver.
wolfSSL/documentation pull request #100
Opened 2023-07-04 21:21 UTC by TakayukiMatsuo

Apply document update in PR83 and PR95 to Japanese version.
Also removed the original unnecessary '\' and '>'. These detract from the appearance of the document.

2023-07-13 20:43 UTC, miyazakh requested changes

2023-07-13 20:43 UTC, miyazakh commented on wolfSSL/src-ja/chapter02.md
> +## NXPCAAMのビルド
"NXP" と "CAAM"　の間にスペース

2023-07-13 20:43 UTC, miyazakh commented on wolfSSL/src-ja/chapter02.md
> +
「拡張されました」は、「拡張しました」がいいと思います。

2023-07-13 20:43 UTC, miyazakh commented on wolfSSL/src-ja/chapter02.md
> +NXP HSM ライブラリをダウンロードして必要なzlibが見つかるようにMakefileを調整します。
原文が、Makefile (or environment variables)　なので、「Makefile や環境変数を調整します。」が良いと思います。

2023-07-17 07:29 UTC, TakayukiMatsuo commented on wolfSSL/src-ja/chapter02.md
> +## NXPCAAMのビルド
対応しました。

2023-07-17 07:29 UTC, TakayukiMatsuo commented on wolfSSL/src-ja/chapter02.md
> +
対応しました。

2023-07-17 07:30 UTC, TakayukiMatsuo commented on wolfSSL/src-ja/chapter02.md
> +NXP HSM ライブラリをダウンロードして必要なzlibが見つかるようにMakefileを調整します。
対応しました。

2023-07-18 22:34 UTC, miyazakh approved these changes

2023-07-18 22:35 UTC, merged