Updated whitespace and removed duplicate entry in wolf Object echoserver
wolfSSL/documentation pull request #128
Opened 2024-05-24 19:57 UTC by rlm2002

2024-05-24 20:41 UTC, JacobBarthelmeh requested changes

2024-05-24 20:41 UTC, JacobBarthelmeh commented on wolfSSL/src/chapter11.md
> -A WOLFSSL object needs to be created after each TCP Connect and the socket file descriptor needs to be associated with the session.
Let's keep this sentence here. To be clear that a new object is needed per file descriptor

2024-05-24 20:41 UTC, JacobBarthelmeh commented on wolfSSL/src/chapter11.md
> -A WOLFSSL object needs to be created after each TCP Connect and the socket file descriptor needs to be associated with the session.
The rest though can be deleted.

2024-05-28 16:44 UTC, JacobBarthelmeh approved these changes

2024-05-28 17:51 UTC, dgarske approved these changes

2024-05-28 17:51 UTC, merged