Add Japanese support for wolfSSL-FIPS-Ready
wolfSSL/documentation pull request #129
Opened 2024-05-25 16:13 UTC by tamasan238

2024-05-30 04:19 UTC, kojo1 requested changes

2024-05-31 01:22 UTC, tamasan238 commented on wolfSSL-FIPS-Ready/mkdocs-ja.yml
> +  language: en
ほかの製品のmkdocs-ja.ymlのlanguageに倣ってenとしていましたが，確かにjaのほうが望ましいですね．

a. このファイルだけjaに変更してcommit
b. 一旦enのままcommitし，他の製品とあわせてすべてlangをjaに修正するPRを作成
c. このファイルについてはjaに修正した上でcommitし，他の製品については別途PRを作成

いかがしましょうか．
jaに変更してビルドしたところ，以下の差分がありました．
- pdf: 見た目上の差分なし(binary diffは差分ありと出力)
- html: フォントサイズが異なる

2024-06-01 00:05 UTC, kojo1 commented on wolfSSL-FIPS-Ready/mkdocs-ja.yml
> +  language: en
では、全部まとめてlanguageだけ変更するPRとしましょうか。

2024-06-02 09:10 UTC, tamasan238 commented on wolfSSL-FIPS-Ready/mkdocs-ja.yml
> +  language: en
承知しました．

2024-06-04 00:33 UTC, kojo1 approved these changes

2024-06-12 00:39 UTC, merged