wolfHSM-docs to wolfSSL-documentation integration - wolfHSM Manual
wolfSSL/documentation pull request #131
Opened 2024-06-05 04:28 UTC by aidangarske

Progress with wolfHSM documentation generation. The wolfHSM does not yet have API documentation, so the Doxygen steps are being skipped. 
Only the src/*.md files are being used for the HTML and PDF manuals. 
updated the mkdocs.yml and took out the summary because it is not necessary in documentations repo.
complete wolfHSM manual for the documentation repo.

2024-06-05 15:46 UTC, dgarske commented
The failure is due to the existing `#17 1.500 cat: api/md/tpm2_8h.md: No such file or directory` issue. I'm going to try and fix that right now. 

I locally built `make wolfhsm` and got the error:

```
1.661 pandoc: SUMMARY.md: withBinaryFile: does not exist (No such file or directory)
```
[wolfHSM-Manual.pdf](https://github.com/user-attachments/files/15593154/wolfHSM-Manual.pdf)


Fix pushed. Attached is the wolfHSM User Manual for review.

2024-06-05 16:16 UTC, bigbrett requested changes
Awesome! First quick pass flagging some broken links, spelling errors, and a few suggestions.

2024-06-05 16:16 UTC, bigbrett commented on wolfHSM/src/chapter03.md
> +e server application that is already configured to run on the HSM core and so manual server configuration is not required.*
spurious newline
```suggestion
*Note: A wolfHSM port comes with a reference server application that is already configured to run on the HSM core and so manual server configuration is not required.*
```

2024-06-05 16:16 UTC, bigbrett commented on wolfHSM/src/chapter03.md
> +8. Process client requests using `wh_Server_HandleRequestMessage()`
weird - the nested bullets are rendered as 1.a, 1.b, 1.c, despite them being written as 1.1, 1.2, 1.3. So referring to "step 1.1" in the text is broken

2024-06-05 16:16 UTC, bigbrett commented on wolfHSM/src/chapter04.md
> +### Client/Server APIs:
```suggestion
### Client/Server APIs
```

2024-06-05 16:16 UTC, bigbrett commented on wolfHSM/src/chapter04.md
> +High level client and server APIs (defined in [wh_client.h](wolfhsm/wh_client.h) and [wh_server.h](wolfhsm/wh_server.h)) are the primary interface for communication. These functions abstract the low
source file links don't work - these probably shoudn't be links, lets just make them code

```suggestion
High-level client and server APIs (defined in `wolfhsm/wh_client.h` and `wolfhsm/wh_server.h` are the primary interface for communication. These functions abstract the low level communications details from the caller, providing a simple split transaction interface for logical operations.
```

2024-06-05 16:16 UTC, bigbrett commented on wolfHSM/src/chapter04.md
> +The wolfHSM library provides comprehensive key management capabilities, including storing, loading, and exporting keys from non-volatile memory, caching of frequently used keys in RAM for fast access
broken links, markdown files were renamed

2024-06-05 16:16 UTC, bigbrett commented on wolfHSM/src/chapter05.md
> +The client library API is the primary mechanism through which users will interact with wolfHSM. Refer to the [API documentation](appendix01-api-reference.md) for a full list of available functions an
broken link

2024-06-05 16:16 UTC, bigbrett commented on wolfHSM/src/chapter05.md
> +For objects that should not be copied and sent over the transport, there exist DMA versions of the `NvmAddObject` functions. These pass the data to the server by reference rather than by value, allow
broken link - should point to DMA callbacks in chapter 7

2024-06-05 16:16 UTC, bigbrett commented on wolfHSM/src/chapter05.md
> +For a full description of all the NVM API functions, please refer to the [API documentation](todo).
broken link

2024-06-05 16:16 UTC, bigbrett commented on wolfHSM/src/chapter05.md
> +If wolfHSM does not yet support that algorithm, the API call will return `CRYPTOCB_UNAVAILABLE`. See [supported wolfCrypt algorithms](todo) for the full list of algorithms wolfHSM supports for remote
broken link, but this section doesn't exist. I can add it in a PR later

2024-06-05 16:16 UTC, bigbrett commented on wolfHSM/src/chapter07.md
> +For a full list of wolfHSM configuration settings that can be defined in `wh_config.h`, refer to the [API documentation](appendix01-api-reference.md).
broken link

2024-06-05 16:16 UTC, bigbrett commented on wolfHSM/src/chapter08.md
> +- RAM-based and file-based NVM flash simulators
POSIX should be all-caps, it is an acronym

2024-06-05 16:19 UTC, bigbrett commented
@aidangarske You mentioned that we don't yet have doxygen - we do have the client and server APIs doxygen-commented, but it is inline in the source code (as opposed to maintained separately like wolfSSL does in this repo). There isnt a doxyfile yet though. Just FYI on where that is at

2024-06-05 16:28 UTC, dgarske commented
> @aidangarske You mentioned that we don't yet have doxygen - we do have the client and server APIs doxygen-commented, but it is inline in the source code (as opposed to maintained separately like wolfSSL does in this repo). There isnt a doxyfile yet though. Just FYI on where that is at

Aidan is OOO today, but Ruby can help. Brett if you have API's that are public that you would like Doxygen to process please provide a link to those. Aidan and I could not find them.

```
/*!
    \ingroup Client Functions
    \brief Description of function

    \return 0=

    \param arg1 description 

    _Example_
    \code
    int rc = CallFunc();
    \endcode

    \sa OtherFunction
*/
```

Thanks

2024-06-05 16:38 UTC, bigbrett commented
> > @aidangarske You mentioned that we don't yet have doxygen - we do have the client and server APIs doxygen-commented, but it is inline in the source code (as opposed to maintained separately like wolfSSL does in this repo). There isnt a doxyfile yet though. Just FYI on where that is at
> 
> @aidangarske is OOO today, but @rlm2002 can help. Brett if you have API's that are public that you would like Doxygen to process please provide a link to those. Aidan and I could not find them.
> 
> ```
> /*!
>     \ingroup Client Functions
>     \brief Description of function
> 
>     \return 0=
> 
>     \param arg1 description 
> 
>     _Example_
>     \code
>     int rc = CallFunc();
>     \endcode
> 
>     \sa OtherFunction
> */
> ```
> 
> Thanks

@rlm2002 here ya go:

- client API: https://github.com/wolfSSL/wolfHSM/blob/main/wolfhsm/wh_client.h
- server API: https://github.com/wolfSSL/wolfHSM/blob/main/wolfhsm/wh_server.h

2024-06-06 15:02 UTC, JacobBarthelmeh approved these changes

2024-06-06 15:04 UTC, JacobBarthelmeh commented
Changes look good to me as a nice first step to adding the wolfHSM manual. The github actions is complaining about:

```
> [wolfssl-stage1 2/2] RUN make pdf V=:
0.992 [info] Loading docs/xml/wh__flash_8h.xml
0.992 [info] Loading docs/xml/wh__error_8h.xml
Warning: 0.993 [warning] Failed to parse member wh__error_8h error: basic_string: construction from null is not valid
0.993 [info] Loading docs/xml/wh__common_8h.xml
Warning: 0.994 [warning] Failed to parse member wh__common_8h error: basic_string: construction from null is not valid
0.994 [info] Loading docs/xml/README_8md.xml
```

2024-06-06 15:05 UTC, dgarske commented
> Changes look good to me as a nice first step to adding the wolfHSM manual. The github actions is complaining about:
> 
> ```
> > [wolfssl-stage1 2/2] RUN make pdf V=:
> 0.992 [info] Loading docs/xml/wh__flash_8h.xml
> 0.992 [info] Loading docs/xml/wh__error_8h.xml
> Warning: 0.993 [warning] Failed to parse member wh__error_8h error: basic_string: construction from null is not valid
> 0.993 [info] Loading docs/xml/wh__common_8h.xml
> Warning: 0.994 [warning] Failed to parse member wh__common_8h error: basic_string: construction from null is not valid
> 0.994 [info] Loading docs/xml/README_8md.xml
> ```

Those are fixed with https://github.com/wolfSSL/wolfHSM/pull/42
Caused by unnamed enums and unions.
Once that PR is merged this should work. I've tested locally.

2024-06-06 15:36 UTC, JacobBarthelmeh commented
@bigbrett it the request for changes still outstanding? Am okay merging in this initial documentation addition as is.

2024-06-06 15:39 UTC, bigbrett commented
> @bigbrett is the request for changes still outstanding? Am okay merging in this initial documentation addition as is.

@JacobBarthelmeh let me take a peek. I'll approve if they are all addressed, otherwise I'll request changes.

2024-06-06 15:52 UTC, bigbrett approved these changes
@JacobBarthelmeh good to go.

@dgarske @aidangarske thank you both so much for your help on this. Go Team Garske!!!

@dgarske @JacobBarthelmeh Regarding the doxybook2 error, naming the enums is fine, but naming the unions will require changes to the calling code to work. We might end up doing that, or we may just pull docs into a separate header like wolfSSL does. Will discuss with the team. I don't think anonymous unions are critical to funcitonality, so we might just bite the bullet and refactor in this case. I'll keep you in the loop, but go ahead and merge for now without the API docs live.

2024-06-06 15:54 UTC, merged