Japanese version
wolfSSL/documentation pull request #87
Opened 2023-01-28 04:31 UTC by kojo1

$ make DOC_LANG=JA

2023-01-30 07:04 UTC, TakayukiMatsuo requested changes

2023-01-30 07:04 UTC, TakayukiMatsuo commented on wolfSSL-Porting/src-ja/section04.md
> +wolfSSLは、お客様が新しい環境にwolfSSLを移植できるためのサポートパッケージとコンサルティングサービスを提供しています。
この行はすぐ上の行と重複しています。削除してください。

2023-01-30 07:24 UTC, kojo1 commented on wolfSSL-Porting/src-ja/section01.md
> +のガイドは、デフォルトでサポートされていない新しいプラットフォームまたは環境に wolfSSL および wolfCrypt を移植する開発者またはエンジニアを対象としています。
fixed

2023-01-30 07:27 UTC, kojo1 commented on wolfSSL-Porting/src-ja/section02.md
> +There are two additional data types used by wolfSSL and wolfCrypt, called “word32” and “word16”.  The default type mappings for these are:
fixed

2023-01-30 07:27 UTC, kojo1 commented on wolfSSL-Porting/src-ja/section02.md
> +一部の操作で利用可能な場合、wolfSSL は 64 ビット型を使用します。 wolfSSL ビルドは、SIZEOF_LONG と SIZEOF_LONG_LONG の設定に基づいて、word64 の正しい基本データ型を検出して設定しようとします。 2 つの 32 ビット型が一緒に使用される、真の 64 ビット型を持たない一部のプラットフォームでは、パフォーマンスが低下する可能性があります。 6
fixed

2023-01-30 07:27 UTC, kojo1 commented on wolfSSL-Porting/src-ja/section02.md
> +デフォルトでは、wolfSSLは/dev/urandomまたは/dev/randomを使用してRNGシードを生成します。 NO_DEV_RANDOMの定義は、デフォルトのwc_GenerateSeed（）関数を無効にするwときにビルド時に指定します。これが指定されている場合は、ターゲットプラットフォームに固有の./wolfcrypt/src/random.cにカスタムwc_GenerateSee
fixed

2023-01-30 07:27 UTC, kojo1 commented on wolfSSL-Porting/src-ja/section02.md
> +- ECC符号コールバック
fixed

2023-01-30 07:27 UTC, kojo1 commented on wolfSSL-Porting/src-ja/section04.md
> +wolfSSLは、お客様が新しい環境にwolfSSLを移植できるためのサポートパッケージとコンサルティングサービスを提供しています。
fixed

2023-01-31 00:32 UTC, TakayukiMatsuo approved these changes

2023-01-31 18:29 UTC, cconlon approved these changes

2023-01-31 18:29 UTC, merged