wolfSentry in Japanese
wolfSSL/documentation pull request #88
Opened 2023-01-28 22:47 UTC by kojo1

make DOC_LANG=JA

2023-01-30 08:56 UTC, TakayukiMatsuo requested changes

2023-01-30 08:56 UTC, TakayukiMatsuo commented on wolfSentry/src-ja/chapter02.md
> +unzip を使用する場合は、`-a` 修飾子を有効にします。 unzip のマニュアル ページから、`-a` 修飾子の機能は次のとおりです。
"修飾子の機能は次のとおりです。説明された："  >> "修飾子の機能は次のように説明されています：”

2023-01-30 08:56 UTC, TakayukiMatsuo commented on wolfSentry/src-ja/chapter02.md
> +> [...] -a オプションを指定すると、zip で識別されるファイルがテキスト ファイル (zipinfo で「t」ラベルが付いているファイル) として識別されます。
引用文中の"[...]"は不要かもしれません。
また、引用文の訳は、
”-a オプションを指定すると、zip によってテキスト ファイルとして識別されるファイル (zipinfo リストで、'b' ではなく、't' ラベルが付いているファイル) が自動的に抽出され、行末、ファイル終了文字、文字が必要に応じて変換されます。”
が適切かもしれません。

2023-01-30 08:56 UTC, TakayukiMatsuo commented on wolfSentry/src-ja/chapter02.md
> +デフォルトのビルドでは、wolfSentry は POSIX ランタイム、特にヒープ アロケータ、clock_gettime、stdio、セマフォ、および文字列 API に依存しています。 ただし、これらの依存関係は、さまざまなビルド時のオプションで回避できます。 特にレシピは
”特にレシピは”　>> "特に、次の指定を用いると：”　などに言い換えが必要かも。

2023-01-30 08:56 UTC, TakayukiMatsuo commented on wolfSentry/src-ja/chapter02.md
> +少数の基本的な文字列関数のみに依存する libwolfsentry.a を生成します。 次に、アロケータと時間のコールバックを `struct で設定する必要があります
`struct で設定する必要があります`wolfsentry_init()` に供給される wolfsentry_host_platform_interface`。

の部分は語順を変える必要あり。

`wolfsentry_init()` に渡される　`wolfsentry_host_platform_interface`構造体に

2023-01-30 08:56 UTC, TakayukiMatsuo commented on wolfSentry/src-ja/chapter02.md
> +テスト スイートをビルドして実行するには、`make -j test` または `make V=1 -j test` を詳細に使用できます。
または `make V=1 -j test` を詳細に使用できます。　>> 　または詳細な出力が必要ならば `make V=1 -j test` を使用できます。

2023-01-30 08:56 UTC, TakayukiMatsuo commented on wolfSentry/src-ja/chapter02.md
> +| | `make` オプション | 説明 |
この表はレイアウトが崩れています。以下と置換してください。

| `make` オプション | 説明 |
| --------------| ------------|
| `V` | 詳細な `make` 出力 <br> 指定例： `make V=1 -j test`|
| `USER_MAKE_CONF` | ユーザー定義の Makefileを含める<br> 指定例： `make -j USER_MAKE_CONF=Makefile.settings` |
| `SRC_TOP` | ソース コードの最上位ディレクトリ (デフォルトは「pwd -P」) |
| `BUILD_TOP`| 別の場所 (ソース ツリーの外部またはサブディレクトリ内) にアーティファクトを使用してビルドする <br> 指定例： `make BUILD_TOP=./build -j test`|
| `DEBUG` | 使用するコンパイラ デバッグ フラグ (デフォルトは `-ggdb`) |
| `OPTIM` | 使用するオプティマイザ フラグ (デフォルトは `-O3`) |
| `C_WARNFLAGS` | 使用する警告フラグ (デフォルト [^1] を参照) |
| `NO_STDIO` | プラットフォームで"STDIO"が提供されていません |
| `NO_JSON` | JSON 構成サポートをコンパイルしない |
| `USER_SETTINGS_FILE`| インクルードする追加のヘッダー ファイル |
| `SINGLETHEADED` | シングル スレッドの使用にスレッド セーフ セマンティクスを使用しない<br> 指定例： `make -j SINGLETHREADED=1 テスト` |
| `STATIC` | 静的ライブラリを構築 |
| `STRIPPED` | バイナリからデバッグシンボルを削除 |
| `BUILD_DYNAMIC` | 動的ライブラリを構築 |
| `VERY_QUIET` | 非常に静かなビルドを有効にする |
| `TAR` | `make dist` の GNU tar バイナリへのパス。macOS では `gtar` に設定する必要があります |
| `VERSION` | コンパイルするバージョン番号 (デフォルトは [^2] を参照) |

2023-01-30 08:56 UTC, TakayukiMatsuo commented on wolfSentry/src-ja/chapter02.md
> +```
”```”は削除

2023-01-30 08:56 UTC, TakayukiMatsuo commented on wolfSentry/src-ja/chapter02.md
> +| | プリプロセッサ マクロ | 説明 |
この表はレイアウトが壊れています。以下と置換してください。

| プリプロセッサ マクロ | 説明 |
| ------------------- | ----------- |
| `WOLFSENTRY_NO_STDIO` | プラットフォームに「STDIO」がありません |
| `WOLFSENTRY_NO_JSON` | JSON 構成サポートをコンパイルしない |
| `WOLFSENTRY_USER_SETTINGS_FILE` | インクルードする追加のヘッダー ファイル |
| `WOLFSENTRY_SINGLETHREADED` | シングル スレッドの使用にスレッド セーフ セマンティクスを使用しない |
| `CENTIJSON_USE_LOCALE` | JSON パーサーはロケール依存の文字を使用する必要があります |
| `WOLFSENTRY_NO_PROTOCOL_NAMES` | 構成ファイルのプロトコル名のサポートを無効にする |
| `DEBUG_JSON` | JSON パーサーにデバッグ `printf()` を追加 |
| `WOLFSENTRY_NO_ERROR_STRINGS` | エラー文字列関数へのエラー コードを無効にする |
| `WOLFSENTRY_NO_MALLOC_BUILTINS` | 組み込みの malloc 関数を無効にする |
| `WOLFSENTRY_HAVE_NONGNU_ATOMICS` | アトミックは非 GNU です (`SINGLETHREADED` が設定されている場合は無視されます) |
| `WOLFSENTRY_NO_CLOCK_BUILTIN` | Bulitin 時間関数を使用しない |
| `WOLFSENTRY_LWIP` | wolfSentry を BSD ソケットではなく LWIP に対して構築 |
| `FREERTOS` | FreeRTOS サポートでビルド |

2023-01-30 08:56 UTC, TakayukiMatsuo commented on wolfSentry/src-ja/chapter04.md
> +## wolfSSL 統合の例
”wolfSSL 統合の例”　>> ”wolfSSLと統合したサンプルプログラム”

2023-01-30 08:56 UTC, TakayukiMatsuo commented on wolfSentry/src-ja/chapter04.md
> +## wolfSentryの例
"例”は”サンプルプログラム”に変更が必要。以降の行にも同様の変更必要箇所あり。

2023-01-30 08:56 UTC, TakayukiMatsuo commented on wolfSentry/src-ja/chapter04.md
> +#### 歩哨.c
”歩哨.c”　>> "sentry.c"

2023-01-30 10:40 UTC, kojo1 commented on wolfSentry/src-ja/chapter02.md
> +<https://www.wolfssl.com/download>
fixed

2023-01-30 10:40 UTC, kojo1 commented on wolfSentry/src-ja/chapter02.md
> +unzip を使用する場合は、`-a` 修飾子を有効にします。 unzip のマニュアル ページから、`-a` 修飾子の機能は次のとおりです。
fixed

2023-01-30 10:40 UTC, kojo1 commented on wolfSentry/src-ja/chapter02.md
> +> [...] -a オプションを指定すると、zip で識別されるファイルがテキスト ファイル (zipinfo で「t」ラベルが付いているファイル) として識別されます。
fixed

2023-01-30 10:41 UTC, kojo1 commented on wolfSentry/src-ja/chapter02.md
> +デフォルトのビルドでは、wolfSentry は POSIX ランタイム、特にヒープ アロケータ、clock_gettime、stdio、セマフォ、および文字列 API に依存しています。 ただし、これらの依存関係は、さまざまなビルド時のオプションで回避できます。 特にレシピは
fixed

2023-01-30 10:41 UTC, kojo1 commented on wolfSentry/src-ja/chapter02.md
> +少数の基本的な文字列関数のみに依存する libwolfsentry.a を生成します。 次に、アロケータと時間のコールバックを `struct で設定する必要があります
fixed

2023-01-30 10:41 UTC, kojo1 commented on wolfSentry/src-ja/chapter02.md
> +```
fixed

2023-01-30 10:41 UTC, kojo1 commented on wolfSentry/src-ja/chapter02.md
> +| | プリプロセッサ マクロ | 説明 |
fixed

2023-01-30 10:41 UTC, kojo1 commented on wolfSentry/src-ja/chapter04.md
> +## wolfSSL 統合の例
fixed

2023-01-30 10:41 UTC, kojo1 commented on wolfSentry/src-ja/chapter04.md
> +## wolfSentryの例
fixed

2023-01-30 10:41 UTC, kojo1 commented on wolfSentry/src-ja/chapter04.md
> +#### 歩哨.c
fixed

2023-02-01 21:48 UTC, miyazakh commented on wolfSentry/src-ja/chapter02.md
> +
-a オプションを使用すると、zip によってテキスト ファイルとして識別されるファイル (zipinfo リストで「b」ではなく「t」ラベルが付いているファイル) が自動的に抽出され、行末、ファイル終了文字、および文字が変換されます。 必要に応じて設定します。

2023-02-01 21:48 UTC, miyazakh commented on wolfSentry/src-ja/chapter04.md
> +
`sh` の出力は原文のまま（英語）でよいと思います。

2023-02-01 21:48 UTC, miyazakh commented on wolfSentry/src-ja/chapter04.md
> +
sh の出力は原文のまま（英語）でよいと思います

2023-02-01 21:48 UTC, miyazakh commented on wolfSentry/src-ja/chapter04.md
> +
`sh` で出力は原文のまま（英語）でよいと思います

2023-02-01 21:48 UTC, miyazakh commented on wolfSentry/src-ja/chapter04.md
> +#define WOLFSENTRY_NO_PROTOCOL_NAMES
#define FREERTOS
#define WOLFSENTRY_SINGLETHREADED
#define WOLFSENTRY_LWIP

2023-03-06 21:42 UTC, kojo1 commented on wolfSentry/src-ja/chapter02.md
> +
fixed

2023-03-06 21:42 UTC, kojo1 commented on wolfSentry/src-ja/chapter04.md
> +
fixed

2023-03-06 21:42 UTC, kojo1 commented on wolfSentry/src-ja/chapter04.md
> +
fixed

2023-03-06 21:44 UTC, kojo1 commented on wolfSentry/src-ja/chapter04.md
> +#define WOLFSENTRY_NO_PROTOCOL_NAMES
fixed

2023-03-07 11:44 UTC, miyazakh approved these changes

2023-03-08 18:03 UTC, cconlon approved these changes

2023-03-08 18:05 UTC, merged